repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      name: Black Python code formatting
      # entry: bash -c 'black "$@" || true' -- # doesn't block commit on fail
      entry: black # block commit on fail
      language: python
      # language_version: python3.9
      types: [python]
      args: [
        "--check",
        "--diff",
        "--skip-string-normalization",
        ]
      fail_fast: true
      verbose: true
      exclude: ^migrations/
      log_file: precommit_black.log

  - repo: https://github.com/pycqa/isort
    rev: 5.10.0
    hooks:
      - id: isort
        name: Sorting import statements
        # entry: bash -c 'isort "$@" || true' --  # doesn't block commit on fail
        entry: isort # block commit on fail
        language: python
        # language_version: python3.9
        args: [
          "--check-only",
          "--diff",
          "-l=88",
          "--skip=migrations",
          "--profile=black",
          ]
        fail_fast: true
        verbose: true
        exclude: ^migrations/
        log_file: precommit_isort.log

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      language: python
      # language_version: python3.9
      # entry: bash -c 'flake8 "$@" || true' -- # doesn't block commit on fail
      entry: flake8 # block commit on fail
      args: ["--max-line-length=91"]
      fail_fast: true
      verbose: true
      exclude: ^migrations/
      log_file: precommit_flake.log